# Generated by Django 6.0.2 on 2026-02-24 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_delete_wishlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('MK', 'Milk'), ('LS', 'Lassi'), ('BS', 'Basundi'), ('MT', 'Matho'), ('SW', 'Sweets'), ('IC', 'Icecream')], max_length=2),
        ),
    ]
