# Generated by Django 6.0.2 on 2026-03-11 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_orderplaced_delivery_notes_alter_orderplaced_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='quantity',
            field=models.FloatField(default=10),
        ),
    ]
