# Generated by Django 6.0.2 on 2026-02-24 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_orderplaced_cust_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Wishlist',
        ),
    ]
