# Generated by Django 6.0.2 on 2026-02-27 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_product_expiry_date_product_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='price',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='cart',
            name='size',
            field=models.CharField(default='500gm', max_length=50),
        ),
        migrations.AddField(
            model_name='orderplaced',
            name='price',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='orderplaced',
            name='size',
            field=models.CharField(default='500gm', max_length=50),
        ),
    ]
