# Generated by Django 6.0.2 on 2026-03-11 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_alter_product_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderplaced',
            name='delivery_otp',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
